/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

/**
 *
 * @author Geiner-ZF
 */
public class JframeView extends javax.swing.JFrame {

    /**
     * Creates new form ViewJframe
     */
    public JframeView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Comensal1txt = new javax.swing.JTextField();
        Comensal1Lbl = new javax.swing.JLabel();
        Comensal1Lbl1 = new javax.swing.JLabel();
        Comensal1txt6 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        Comensal1Lbl2 = new javax.swing.JLabel();
        Comensal1txt7 = new javax.swing.JTextField();
        Comensal1Lbl3 = new javax.swing.JLabel();
        Comensal1txt8 = new javax.swing.JTextField();
        Comensal1Lbl4 = new javax.swing.JLabel();
        Comensal1txt9 = new javax.swing.JTextField();
        Comensal1Lbl5 = new javax.swing.JLabel();
        Comensal1txt10 = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        Comensal1Lbl6 = new javax.swing.JLabel();
        Comensal1txt11 = new javax.swing.JTextField();
        Comensal1Lbl7 = new javax.swing.JLabel();
        Comensal1txt12 = new javax.swing.JTextField();
        Comensal1Lbl8 = new javax.swing.JLabel();
        Comensal1txt13 = new javax.swing.JTextField();
        Comensal1Lbl9 = new javax.swing.JLabel();
        Comensal1txt14 = new javax.swing.JTextField();
        Comensal1Lbl10 = new javax.swing.JLabel();
        Comensal1txt15 = new javax.swing.JTextField();
        Comensal1Lbl11 = new javax.swing.JLabel();
        Comensal1txt16 = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 102));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 153));
        jLabel1.setText("          Desarrollado por:");

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("MARMITA");

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("                       Geiner Zúñiga - Melany Lawson - Kriscia Campos - Maria del Mar Acón - Alfieri Mora");

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Agregar Canibal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        Comensal1txt.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txtActionPerformed(evt);
            }
        });

        Comensal1Lbl.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl.setText("ID Comensal 1 :");

        Comensal1Lbl1.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl1.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl1.setText("Nombre Comensal :");

        Comensal1txt6.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt6ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText(" Comensales atendidos");

        jTextField1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N

        Comensal1Lbl2.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl2.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl2.setText("ID Comensal 2 :");

        Comensal1txt7.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt7ActionPerformed(evt);
            }
        });

        Comensal1Lbl3.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl3.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl3.setText("Nombre Comensal :");

        Comensal1txt8.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt8ActionPerformed(evt);
            }
        });

        Comensal1Lbl4.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl4.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl4.setText("ID Comensal 3 :");

        Comensal1txt9.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt9ActionPerformed(evt);
            }
        });

        Comensal1Lbl5.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl5.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl5.setText("Nombre Comensal :");

        Comensal1txt10.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt10ActionPerformed(evt);
            }
        });

        Comensal1Lbl6.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl6.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl6.setText("ID Comensal 3 :");

        Comensal1txt11.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt11ActionPerformed(evt);
            }
        });

        Comensal1Lbl7.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl7.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl7.setText("Nombre Comensal :");

        Comensal1txt12.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt12ActionPerformed(evt);
            }
        });

        Comensal1Lbl8.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl8.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl8.setText("ID Comensal 3 :");

        Comensal1txt13.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt13ActionPerformed(evt);
            }
        });

        Comensal1Lbl9.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl9.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl9.setText("Nombre Comensal :");

        Comensal1txt14.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt14ActionPerformed(evt);
            }
        });

        Comensal1Lbl10.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl10.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl10.setText("ID Comensal 3 :");

        Comensal1txt15.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt15ActionPerformed(evt);
            }
        });

        Comensal1Lbl11.setBackground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl11.setForeground(new java.awt.Color(0, 0, 0));
        Comensal1Lbl11.setText("Nombre Comensal :");

        Comensal1txt16.setBackground(new java.awt.Color(255, 255, 255));
        Comensal1txt16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Comensal1txt16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel4))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Comensal1Lbl1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Comensal1Lbl9)
                                    .addComponent(Comensal1Lbl8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Comensal1txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Comensal1txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Comensal1txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Comensal1Lbl)
                                .addGap(32, 32, 32)
                                .addComponent(Comensal1txt, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addComponent(Comensal1Lbl2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(192, 192, 192)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Comensal1Lbl6)
                                    .addComponent(Comensal1Lbl3)
                                    .addComponent(Comensal1Lbl10)
                                    .addComponent(Comensal1Lbl11)))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Comensal1Lbl5)
                            .addComponent(Comensal1Lbl4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Comensal1txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Comensal1txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Comensal1Lbl7)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Comensal1txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comensal1txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comensal1txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comensal1txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Comensal1txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(Comensal1txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comensal1txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comensal1Lbl)
                    .addComponent(Comensal1Lbl2)
                    .addComponent(Comensal1txt7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Comensal1Lbl1)
                            .addComponent(Comensal1Lbl3)
                            .addComponent(Comensal1txt8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(Comensal1txt6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Comensal1Lbl6)
                            .addComponent(Comensal1txt15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Comensal1Lbl4)
                            .addComponent(Comensal1txt9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Comensal1Lbl5)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Comensal1txt10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Comensal1txt12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(Comensal1Lbl7))
                .addGap(48, 48, 48)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comensal1Lbl8)
                    .addComponent(Comensal1txt13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comensal1Lbl10)
                    .addComponent(Comensal1txt11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comensal1Lbl9)
                    .addComponent(Comensal1txt14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Comensal1Lbl11)
                    .addComponent(Comensal1txt16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jButton1)
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(422, 422, 422)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 241, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jButton1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(109, 109, 109))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Comensal1txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Comensal1txt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt6ActionPerformed

    private void Comensal1txt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt7ActionPerformed

    private void Comensal1txt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt8ActionPerformed

    private void Comensal1txt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt9ActionPerformed

    private void Comensal1txt10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt10ActionPerformed

    private void Comensal1txt11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt11ActionPerformed

    private void Comensal1txt12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt12ActionPerformed

    private void Comensal1txt13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt13ActionPerformed

    private void Comensal1txt14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt14ActionPerformed

    private void Comensal1txt15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt15ActionPerformed

    private void Comensal1txt16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Comensal1txt16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Comensal1txt16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JframeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JframeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JframeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JframeView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JframeView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Comensal1Lbl;
    private javax.swing.JLabel Comensal1Lbl1;
    private javax.swing.JLabel Comensal1Lbl10;
    private javax.swing.JLabel Comensal1Lbl11;
    private javax.swing.JLabel Comensal1Lbl2;
    private javax.swing.JLabel Comensal1Lbl3;
    private javax.swing.JLabel Comensal1Lbl4;
    private javax.swing.JLabel Comensal1Lbl5;
    private javax.swing.JLabel Comensal1Lbl6;
    private javax.swing.JLabel Comensal1Lbl7;
    private javax.swing.JLabel Comensal1Lbl8;
    private javax.swing.JLabel Comensal1Lbl9;
    private javax.swing.JTextField Comensal1txt;
    private javax.swing.JTextField Comensal1txt10;
    private javax.swing.JTextField Comensal1txt11;
    private javax.swing.JTextField Comensal1txt12;
    private javax.swing.JTextField Comensal1txt13;
    private javax.swing.JTextField Comensal1txt14;
    private javax.swing.JTextField Comensal1txt15;
    private javax.swing.JTextField Comensal1txt16;
    private javax.swing.JTextField Comensal1txt6;
    private javax.swing.JTextField Comensal1txt7;
    private javax.swing.JTextField Comensal1txt8;
    private javax.swing.JTextField Comensal1txt9;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
